variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "1"
   ORD_SOUMET_M: "8G"
   ORD_SOUMET_TMPFS: "1G"
stages:
   - build
   - test
   - package
   - deploy

before_script:
   - source ~/ci-admin/env/init.sh
   - export PIPELINE_SUBDIR=${ECCI_BUILD_DIR}/precaution/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}

#----- rhel-8-icelake-64_inteloneapi-2022.1.2

build:rhel-8-icelake-64_inteloneapi-2022.1.2:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

package:rhel-8-icelake-64_inteloneapi-2022.1.2:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - tags
      - dev
      - schedules
   dependencies:
      - build:rhel-8-icelake-64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-icelake-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-icelake-64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_inteloneapi-2022.1.2

build:rhel-8-amd64_inteloneapi-2022.1.2:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

package:rhel-8-amd64_inteloneapi-2022.1.2:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - tags
      - dev
      - schedules
   dependencies:
      - build:rhel-8-amd64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_gnu-9.3

build:rhel-8-amd64_gnu-9.3.0:
   stage: build
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS

package:rhel-8-amd64_gnu-9.3.0:
   stage: package
   tags:
      - concurrent
   only:
      - master
      - tags
      - dev
      - schedules
   dependencies:
      - build:rhel-8-amd64_gnu-9.3.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/rhel-8-amd-64/gnu-9.3.0.sh 
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_rhel-8-amd64_gnu-9.3.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_inteloneapi-2022.1.2

build:ubuntu-22.04-amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2022.1.2.sh
      - echo ${ORDENV_PLAT} registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - cmake ${SRC_DIR}
      - time make -j $NCPUS
     
package:ubuntu-22.04-amd64_inteloneapi-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2022.1.2
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2022.1.2.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2022.1.2
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_inteloneapi-2023.2.0

build:ubuntu-22.04-amd64_inteloneapi-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2023.2.0.sh
      - echo ${ORDENV_PLAT} registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - cmake ${SRC_DIR}
      - time make -j $NCPUS
     
package:ubuntu-22.04-amd64_inteloneapi-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_inteloneapi-2023.2.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/inteloneapi-2023.2.0.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_inteloneapi-2023.2.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-22.04-amd64_gnu-11.4.0

build:ubuntu-22.04-amd64_gnu-11.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: build
   tags:
      - concurrent
   only:
     - master
     - dev
     - tags
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/gnu.sh
      - set -e
      - mkdir -pv ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - cmake ${SRC_DIR}
      - time make -j 1

package:ubuntu-22.04-amd64_gnu-11.4.0:
   variables:
      ORD_SOUMET_MACH    : gpsc5
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
   stage: package
   tags:
      - concurrent
   only:
      - master
      - dev
      - tags
      - schedules
   dependencies:
      - build:ubuntu-22.04-amd64_gnu-11.4.0
   environment:
      name: testing
   script:
      - set +e
      - source ${ECCI_ENV}/latest/ubuntu-22.04-amd-64/gnu.sh
      - set -e
      - cd ${PIPELINE_SUBDIR}/build_ubuntu-22.04-amd64_gnu-11.4.0
      - make package
      - ~/ci-admin-bundle/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#deploy:staging:
#   stage: deploy
#   only:
#      - master
#      - tags
#      - dev
#      - schedules
#   script:
#      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"
